### ISSUE TITLE
link phone number

### ISSUE THREAD

**Issue by carlarnaud** [pwn0sec/PwnXSS#20]
Hello, 

I have a mistake when the crawler check link tag with a phone number inside : <a href="tel:0123456789">phone contact</a>

`[21:15:28] [CRITICAL] Internal error: No connection adapters were found for 'tel:0800006272'
Traceback (most recent call last):
  File "PwnXSS-master/pwnxss.py", line 73, in <module>
    start()
  File "PwnXSS-master/pwnxss.py", line 54, in start
    crawler.crawl(getopt.u,int(getopt.depth),getopt.proxy,getopt.user_agent,check(getopt),getopt.method,getopt.cookie)
  File "PwnXSS-master/lib/crawler/crawler.py", line 50, in crawl
    self.crawl(url,depth-1,base,proxy,level,method,cookie)
  File "PwnXSS-master/lib/crawler/crawler.py", line 50, in crawl
    self.crawl(url,depth-1,base,proxy,level,method,cookie)
  File "PwnXSS-master/lib/crawler/crawler.py", line 42, in crawl
    urls=self.getLinks(base,proxy,headers,cookie)
  File "PwnXSS-master/lib/crawler/crawler.py", line 19, in getLinks
    text=conn.get(base).text
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'tel:0800006272'`

**Comment by duckstroms** [comment]
fixed release wait for ``v.3``
