### ISSUE TITLE
TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by anatoliyv** [pwn0sec/PwnXSS#7]
Sometimes fails with an exception.

```
Traceback (most recent call last):
  File "pwnxss.py", line 73, in <module>
    start()
  File "pwnxss.py", line 52, in start
    core.main(getopt.u,getopt.proxy,getopt.user_agent,check(getopt),getopt.cookie,getopt.method)
  File "[hidden]/PwnXSS/lib/core.py", line 165, in main
    self.get_method()
  File "[hidden]/PwnXSS/lib/core.py", line 135, in get_method
    _respon=self.session.get(test)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by andripwn** [comment]
**Hi!** @anatoliyv Thanks for findding! , any **Proof On Concept** ?
